#!/bin/bash
title=intel-undervolt
description="undervolts intel cpu by -100mV"
status=off

main() {
	install intel-undervolt intel-undervolt-$INIT
	
	sed -i "s/^undervolt 2 'CPU Cache' 0/undervolt 2 'CPU Cache' -100/g" /etc/intel-undervolt.conf 

	intel-undervolt apply

	service intel-undervolt
	service intel-undervolt-loop
}

