#!/bin/bash
title=pipewire
description="- Pipewire sound system"
status=on

main() {

	install pipewire wireplumber pipewire-alsa pipewire-jack pipewire-pulse 

	SCRIPT_DIR="/usr/local/bin/"
	SCRIPT_SOUND="$SCRIPT_DIR/pipewire-launcher"
	
	mkdir -p $SCRIPT_DIR

	chown "$USERNAME" "$SCRIPT_DIR"
	touch "$SCRIPT_SOUND"
	
	sudo -u "$USERNAME" sudo chmod +x "$SCRIPT_SOUND"

echo "#!/bin/sh
#RedGreen925's script
#https://forum.artixlinux.org/index.php/topic,7606.0.html

# added to start pipewire on kde login added to its autostart.

#/usr/bin/pipewire & /usr/bin/pipewire-pulse & /usr/bin/wireplumber

# kill any existing pipewire instance to restore sound
pkill -u "$USER" -fx /usr/bin/pipewire-pulse 1>/dev/null 2>&1
pkill -u "$USER" -fx /usr/bin/wireplumber 1>/dev/null 2>&1
pkill -u "$USER" -fx /usr/bin/pipewire 1>/dev/null 2>&1

/usr/bin/pipewire &

# wait for pipewire to start before attempting to start related daemons
while [ "$(pgrep -f /usr/bin/pipewire)" = "" ] ; do
   sleep 2
done

/usr/bin/wireplumber &

/usr/bin/pipewire-pulse &" > "SCRIPT_SOUND"


}
