#!/bin/bash
title=throttled
descritpion="helps with cpu throttle, i think its good for laptops. dinit for now"
status=off

main() {
	install throttled

	touch /etc/dinit.d/throttled

	echo "type		= process
command		= /usr/lib/throttled/throttled.py
restart		= false
after		= local.target
before		= login.target " > /etc/dinit.d/throttled

	service throttled
}
